version: '3'

networks:
  exp:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

services:
  redis:
    image: redis:6.2.6
    restart: unless-stopped
    networks:
      exp:
        ipv4_address: 172.21.0.2

  app:
    image: npq7721/rpc-explorer:1.3.0
    restart: unless-stopped
    networks:
      exp:
        ipv4_address: 172.21.0.3
    env_file:
      - .env
    ports:
      - 80:8888

    volumes:
      - /home/tri/workspace/test_explorer/:/applogs